- name: powersettings config
  become: yes
  become_user: sjas
  copy:
    src: powermanagementprofilesrc
    dest: /home/sjas/.config

- name: crit action config
  become: yes
  become_user: sjas
  copy:
    src: powerdevilrc
    dest: /home/sjas/.config