- name: whisper systems apt-key
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc

- name: signal repo 
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal

- name: signal package
  apt:
    name: signal-desktop
    cache_valid_time: 1800