---

- name: kanban include
  import_tasks: 0x01_kanban.yml
  tags: util,kanban

- name: diff-so-fancy include
  import_tasks: 0x02_diff-so-fancy.yml
  tags: util

# - name: nextcloud snap include
#   import_tasks: 0x03_nextcloud.yml
#   tags: util,nextcloud,snap

- name: direnv include
  import_tasks: 0x04_direnv.yml
  tags: util

# - name: keepassxc snap include
#   import_tasks: 0x05_keepassxc.yml
#   tags: util,keepass,snap

- name: scc code counter
  import_tasks: 0x06_scc.yml
  tags: util

- name: bat which sucks to install include
  import_tasks: 0x07_bat.yml
  tags: util,bat

- name: CF mm tools include
  import_tasks: 0x08_mm.yml
  tags: util

- name: xml and json toolset
  import_tasks: 0x09_xml-and-json.yml
  tags: util,xml,json

- name: screenshot tools include
  import_tasks: 0x0a_screenshots.yml
  tags: util,screenshot,shutter,spectacle

- name: simplecurses include
  import_tasks: 0x0b_simplecurses.yml
  tags: util

- name: apache directory studio include
  import_tasks: 0x0c_apache-directory-studio.yml
  tags: util,apacheds

- name: ghidra include
  import_tasks: 0x0d_ghidra.yml
  tags: util,ghidra

- name: dbeaver include
  import_tasks: 0x0e_dbeaver.yml
  tags: util,dbeaver,snap

# - name: nagstamon include
#   import_tasks: 0x0f_nagstamon.yml
#   tags: util,nagstamon

# - name: citrix client include
