---

# https://askubuntu.com/questions/1064722/which-telegram-version-for-ubuntu
- name: telegram via snap
  snap:
    name: telegram-desktop

# this one is broken, need to check out https://github.com/TehDmitry/tg-cli
# - name: telegram-cli via snap
#   snap:
#     name: telegram-cli
