---

- name: kanban
  include: 0x01_kanban.yml
  tags: util

- name: diff-so-fancy
  include: 0x02_diff-so-fancy.yml
  tags: util

- name: tweep
  include: 0x03_tweep.yml
  tags: util

- name: direnv
  include: 0x04_direnv.yml
  tags: util

- name: gosca, go scaffolding
  include: 0x05_gosca.yml
  tags: golang

- name: scc code counter
  include: 0x06_scc.yml
  tags: util

- name: bat
  include: 0x07_bat.yml
  tags: util

- name: CF mm tools
  include: 0x08_mm.yml
  tags: util

- name: xidel
  include: 0x09_xidel.yml
  tags: util

- name: golang dep
  include: 0x0a_go-dep.yml
  tags: golang

- name: simplecurses
  include: 0x0b_simplecurses.yml
  tags: util

- name: dialogrc
  include: 0x0c_dialogrc.yml
  tags: util

- name: jp JSON query tool
  include: 0x0d_jp.yml
  tags: util

- name: jsonfui json explorer
  include: 0x0e_jsonfui.yml
  tags: util

- name: shfmt
  include: 0x0f_shfmt.yml
  tags: util

- name: colorize iptables output
  include: 0x10_colorize_iptables.yml
  tags: util

- name: system stats overview through tmux
  include: 0x11_stats.yml
  tags: util

- name: exa instead of ls
  include: 0x12_exa.yml
  tags: util
