---

- name: directories
  become: yes
  become_user: sjas
  file:
    dest: /home/sjas/{{ item }}
    state: directory
  with_items:
    - bin
    - dl
    - doc
    - etc
    - img
    - mp3
    - pdf
    - prv
    - pub
    - tmpl
    - txt
    - vid
    - wrk
    - etc/.dotfiles
    - .config
    - .local
    - .local/bin
    - go

- name: remove obsolete directories
  file:
    dest: /home/sjas/{{ item }}
    state: absent
  with_items:
    - Downloads
    - Templates
    - Public
    - Documents
    - Music
    - Pictures
    - Videos

- name: fix up folders with kde
  become: yes
  become_user: sjas
  copy:
    src: user-dirs.dirs
    dest: /home/sjas/.config

- name: fix up folder encoding
  become: yes
  become_user: sjas
  copy:
    src: user-dirs.locale
    dest: /home/sjas/.config
